# Generated by Django 4.2.3 on 2024-01-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0002_alter_historicaldata_close_alter_historicaldata_high_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDataNSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('open', models.DecimalField(decimal_places=5, max_digits=7)),
                ('high', models.DecimalField(decimal_places=5, max_digits=7)),
                ('low', models.DecimalField(decimal_places=5, max_digits=7)),
                ('close', models.DecimalField(decimal_places=5, max_digits=7)),
                ('adj_close', models.DecimalField(decimal_places=5, max_digits=7)),
                ('volume', models.IntegerField(default=0)),
            ],
        ),
    ]
