# Generated by Django 4.2.3 on 2024-01-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0003_historicaldatanse'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldatanse',
            name='ticker',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
