# Generated by Django 4.2.3 on 2024-01-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0004_historicaldatanse_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDataNSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='null', max_length=50)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('price', models.DecimalField(decimal_places=5, max_digits=7)),
            ],
        ),
    ]
