# Generated by Django 4.2.3 on 2024-01-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_trading', '0005_livedatanse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livedatanse',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
